version: "3.8"

services:
  puppeteer:
    container_name: browserless-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - configs_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.browserless-api.rule=Host(`api.browserless.bmsoftwarelab.com`)"
      - "traefik.http.routers.browserless-api.entrypoints=websecure"
      - "traefik.http.services.browserless-api.loadbalancer.server.port=3000"
      - "traefik.http.routers.browserless-api.tls=true"
      - "traefik.http.routers.browserless-api.service=browserless-api"
      - "traefik.http.routers.browserless-api.tls.certresolver=leresolver"
      - "traefik.docker.network=configs_default"

networks:
  configs_default:
    external: true
